### ISSUE TITLE
Reader hangs with or/define/cond combination

### ISSUE THREAD

**Issue by dcecile** [justinethier/husk-scheme#200]
When trying to use a higher order function inside of an `(or ...)` form, Husk unexpectedly hung, without even beginning to execute my code.

Here is my reduction of the problem (paste into `huski` to trigger):

```scheme
(lambda ()
  (or
    ((lambda ()
      (define x 'y)
      (cond
        (#t
          x))))))
```

It seems like `(define x ...)` and the `(cond (... x))` reference inside of an `(or ...)` or an `(and ...)` are all required parts for causing the hang (100% CPU).

**Comment by justinethier** [comment]
Good find, I'll need to look into this more tomorrow. 

The code can be simplified somewhat by removing the outer `(lambda ()`.

**Comment by justinethier** [comment]
Fixed `getOrigName` to prevent the possibility of an infinite loop. Thanks for reporting this!

**Comment by dcecile** [comment]
:) No problem (the fix works for me :+1:)
