### ISSUE TITLE
Non sense error when trying to load SRFI-13 reference implementation

### ISSUE THREAD

**Issue by felipelalli** [justinethier/husk-scheme#205]
Reference implementation: http://srfi.schemers.org/srfi-13/srfi-13.scm

```
➜  huski srfi-13.scm
Input does not match a macro pattern: (string-fill! target (string-ref s start) tstart tend)
```

**Comment by justinethier** [comment]
This should be fixed now. I verified srfi-13.scm loads but haven't tested it at all...

**Comment by felipelalli** [comment]
@justinethier I'm sorry, I didn't understand what you have said. Could you please be more specific / clear? Thank you.

**Comment by justinethier** [comment]
This works:

    huski> (load "srfi-13.scm" )
    (lambda (strings . delim+grammar) ...)

I have not actually tested what was loaded from `srfi-13.scm` though.

**Comment by felipelalli** [comment]
This does not work to me:

```
 Version 3.19.1 
                                                                         
huski> (load "srfi-13.scm")
Input does not match a macro pattern: (string-fill! target (string-ref s start) tstart tend)
```

Am I missing something? Old version? Which version should I use?

Thank you.

**Comment by justinethier** [comment]
I just checked in the changes.  You need to get the latest version 3.19.2 from the master branch.

**Comment by felipelalli** [comment]
Ah! Yes. You could just ref this issue like #205 in the commit message, or just add this: 92504c385a7cae9607c3a8a1390ab8c95305a0f7 to this issue, linking them to each other.

Thank you very much!

**Comment by justinethier** [comment]
It is linked: https://github.com/justinethier/husk-scheme/issues/205#ref-commit-92504c3

**Comment by felipelalli** [comment]
> It is linked: #205 (reference)

I am sorry!
