### ISSUE TITLE
Implement "hash-table-ref/default" in SRFI-69

### ISSUE THREAD

**Issue by felipelalli** [justinethier/husk-scheme#206]
The fn "hash-table-ref/default" from SRFI-69 is not implemented.

**Comment by justinethier** [comment]
Thanks for reporting this.

Migrated `hashTblRef` to the EvalFunc's, added support for a default argument, and added `hash-table-ref/default`.

**Comment by felipelalli** [comment]
Related: 34947de25c504a031149d5c4b636fc226d313325
