### ISSUE TITLE
News article

### ISSUE THREAD

**Issue by ShalokShalom** [justinethier/husk-scheme#220]
Wonderful that this project is still alive!

Your homepage tells it has died 4 years ago, is there any incentivize to change that?

It almost turned me off.

http://justinethier.github.io/husk-scheme/news.html
Maybe just mentioning that the project is still active?

**Comment by justinethier** [comment]
Thanks for the feedback @ShalokShalom glad you are interested in this project :)

There was a problem with the Jekyll config file that was preventing the web site from being rebuilt, but it has been fixed now. 

Note that development has slowed on this project. New development is going to depend largely on community contributions.

**Comment by ShalokShalom** [comment]
Thats both fine, wonderful to hear that this goes further :heart:
